name: Cookie Refresh

on:
  schedule:
    - cron: '0 0 * * 1'  # 每周一UTC时间1:00 (北京时间9:00)
  workflow_dispatch:  # 允许手动触发

jobs:
  refresh:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pycryptodome PyNaCl
    
    - name: Run refresh script
      env:
        NETEASE_PHONE: ${{ secrets.NETEASE_PHONE }}
        NETEASE_PASSWORD: ${{ secrets.NETEASE_PASSWORD }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
        NOTIFY_EMAIL: ${{ secrets.NOTIFY_EMAIL }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
      run: python refresh_cookie.py
